# Generated by Django 5.1.2 on 2025-09-25 19:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2020)])),
                ('titulo', models.CharField(help_text='Ex: Chambers Global 2025 - Corporate/M&A', max_length=200)),
                ('deadline_envio', models.DateField(help_text='Data limite para envio')),
                ('inicio_pesquisa', models.DateField(blank=True, null=True)),
                ('fim_pesquisa', models.DateField(blank=True, null=True)),
                ('data_publicacao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NAO_INICIADA', 'Não Iniciada'), ('EM_PREPARACAO', 'Em Preparação'), ('ENVIADA', 'Enviada'), ('PESQUISA_ATIVA', 'Pesquisa Ativa'), ('CONCLUIDA', 'Concluída')], default='NAO_INICIADA', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.anuario')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.area')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Submissões',
                'ordering': ['-ano', 'deadline_envio'],
                'unique_together': {('anuario', 'area', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='SubmissaoReferee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_contato', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONTACTADO', 'Contactado'), ('RESPONDIDO', 'Respondido'), ('NAO_RESPONDEU', 'Não Respondeu'), ('RECUSOU', 'Recusou')], default='PENDENTE', max_length=20)),
                ('data_contato', models.DateTimeField(blank=True, null=True)),
                ('feedback_notas', models.TextField(blank=True)),
                ('tem_conflito', models.BooleanField(default=False)),
                ('override_aprovado', models.BooleanField(default=False)),
                ('justificativa_override', models.TextField(blank=True)),
                ('data_override', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contato')),
                ('submissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referees', to='submissoes.submissao')),
                ('usuario_override', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referee da Submissão',
                'verbose_name_plural': 'Referees das Submissões',
                'unique_together': {('submissao', 'contato')},
            },
        ),
        migrations.CreateModel(
            name='RefereeSupente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_suplencia', models.TextField()),
                ('ativado', models.BooleanField(default=False)),
                ('data_ativacao', models.DateTimeField(blank=True, null=True)),
                ('contato_suplente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contato')),
                ('submissao_referee_principal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suplente', to='submissoes.submissaoreferee')),
            ],
            options={
                'verbose_name_plural': 'Referees Suplentes',
            },
        ),
        migrations.CreateModel(
            name='InteracaoTimesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField()),
                ('horas_trabalhadas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qtd_reunioes', models.PositiveIntegerField(default=0)),
                ('ultimo_contato', models.DateField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.area')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
            options={
                'verbose_name_plural': 'Interações Timesheet',
                'unique_together': {('cliente', 'area', 'ano')},
            },
        ),
    ]
